routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('booking/wizard/{page}', 'BookingController@wizard')->name('booking.wizard');
    Route::get('booking/askdestroy/{id}', 'BookingController@askdestroy')->name('booking.askdestroy');

    Route::get('room/equipment/{id}', 'RoomController@equipment')->name('room.equipment');

    Route::get('slot/askdestroy/{id}', 'SlotController@askdestroy')->name('slot.askdestroy');

    Route::get('grant/create/search_customer', 'GrantController@creatingByExistingCustomer')->name('grant.search_customer');
    Route::get('grant/create/new_customer', 'GrantController@creatingByNewCustomer')->name('grant.new_customer');
    Route::get('grant/document/{id}', 'GrantController@document')->name('grant.document');
    Route::get('grant/askdestroy/{id}', 'GrantController@askdestroy')->name('grant.askdestroy');

    Route::get('contact/askmasscreate', 'ContactController@askCSV')->name('contact.askmasscreate');
    Route::post('contact/masscreate', 'ContactController@importCSV')->name('contact.masscreate');
    Route::get('contact/search', 'ContactController@search')->name('contact.search');
    Route::get('contact/askdestroy/{id}', 'ContactController@askdestroy')->name('contact.askdestroy');

    Route::get('customer/search', 'CustomerController@search')->name('customer.search');
    Route::get('customer/contacts', 'CustomerController@contacts')->name('customer.contacts');
    Route::get('customer/askdestroy/{id}', 'CustomerController@askdestroy')->name('customer.askdestroy');

    Route::post('config/generic', 'ConfigController@generic')->name('config.generic');
    Route::post('config/users', 'ConfigController@users')->name('config.users');
    Route::post('config/equipments', 'ConfigController@equipments')->name('config.equipments');
    Route::post('config/review', 'ConfigController@review')->name('config.review');

    Route::resource('config', 'ConfigController');
    Route::resource('year', 'YearController');
    Route::resource('holiday', 'HolidayController');
    Route::resource('room', 'RoomController');
    Route::resource('customer', 'CustomerController');
    Route::resource('contact', 'ContactController');
    Route::resource('grant', 'GrantController');
    Route::resource('slot', 'SlotController');
    Route::resource('booking', 'BookingController');
});

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

use Log;

use App\Events\SluggableCreating;

use App\Slot;
use App\Holiday;

class Booking extends Model
{
    use SluggableID;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $dispatchesEvents = [
        'creating' => SluggableCreating::class,
    ];

    public function room()
    {
        return $this->belongsTo('App\Room');
    }

    public function equipments()
    {
        return $this->belongsToMany('App\Equipment');
    }

    public function grant()
    {
        return $this->belongsTo('App\Grant');
    }

    public function slots()
    {
        return $this->hasMany('App\Slot');
    }

    public function payments()
    {
        return $this->hasMany('App\Payment');
    }

    public function getPrintableDescriptionAttribute()
    {
        if ($this->grant->bookings()->count() > 1)
            return $this->description;
        else
            return $this->grant->description;
    }

    public function getMacroTypeAttribute()
    {
        switch($this->type) {
            case 'recurring':
                return 'recurring';
                break;

            case 'occasional':
                return 'single';
                break;

            case 'manual':
                return 'manual';
                break;

            default:
                Log::error('Prenotazione di tipo non identificato: ' . $this->type);
                return '';
                break;
        }
    }

    public function getRecursionObjAttribute()
    {
        return json_decode($this->recursion);
    }

    public function getExcludedDaysAttribute()
    {
        return ($this->recursion_obj->excluded ?? []);
    }

    public function getHoursAttribute()
    {
        $hours = 0;

        foreach($this->slots as $slot) {
            $hours += timeToFloat($slot->to) - timeToFloat($slot->from);
        }

        return $hours;
    }

    public function scopeYearly($query)
    {
        $query->where('recursion', 'like', '%yearly%');
    }

    /*
        $days si assume essere l'output di staticGetDays() e affini
    */
    public static function sortDaysByQuarter($days)
    {
        $quarters = (object) [
            'first' => (object) [
                'year' => 0,
                'days' => 0
            ],
            'second' => (object) [
                'year' => 0,
                'days' => 0
            ],
            'third' => (object) [
                'year' => 0,
                'days' => 0
            ],
            'fourth' => (object) [
                'year' => 0,
                'days' => 0
            ],
        ];

        foreach($days as $date => $d) {
            if (!is_null($d->holiday))
                continue;

            list($year, $month, $day) = explode('-', $date);

            if ($month <= 3)
                $q = 'first';
            else if ($month <= 6)
                $q = 'second';
            else if ($month <= 9)
                $q = 'third';
            else
                $q = 'fourth';

            $quarters->$q->days += 1;
            $quarters->$q->year = $year;
        }

        return $quarters;
    }

    public static function staticGetDays($start, $end, $info, $include_holidays = true)
    {
        if (is_string($start))
            $start = new \DateTime($start);
        if (is_string($end))
            $end = new \DateTime($end);

        $days = [];
        $end = $end->modify('+1 days');
        $all_days = new \DatePeriod($start, new \DateInterval('P1D'), $end);
        $excluded_days = $info->excluded ?? [];

        foreach($info->cycle as $cycle) {
            $week_offset = 1;
            $validity_start = 1;
            $validity_end = 31;

            switch($cycle) {
                case 'all':
                    break;
                case 'first':
                    $validity_start = 1;
                    $validity_end = 7;
                    break;
                case 'second':
                    $validity_start = 8;
                    $validity_end = 14;
                    break;
                case 'third':
                    $validity_start = 15;
                    $validity_end = 21;
                    break;
                case 'fourth':
                    $validity_start = 22;
                    $validity_end = 28;
                    break;
                case 'last':
                    $validity_start = 25;
                    $validity_end = 31;
                    break;
                case '2_weeks':
                    $week_offset = 2;
                    break;
                case '3_weeks':
                    $week_offset = 3;
                    break;
                case '4_weeks':
                    $week_offset = 4;
                    break;
                default:
                    Log::error('Tipo ciclicità non identificato: ' . $cycle);
                    break;
            }

            $week_index = 0;

            foreach($all_days as $d) {
                $week_index++;
                if ($week_offset != 1 && $week_index % $week_offset == 0)
                    continue;

                $d_day = $d->format('d');
                if ($d_day < $validity_start || $d_day > $validity_end)
                    continue;

                foreach($info->days as $info_d) {
                    if ($d->format('w') == $info_d->offset) {
                        $fulldate = $d->format('Y-m-d');

                        if (in_array($fulldate, $excluded_days)) {
                            continue;
                        }

                        $days[$fulldate] = (object)[
                            'from' => $info_d->from,
                            'to' => $info_d->to,
                            'holiday' => null
                        ];
                        break;
                    }
                }
            }

            $all_dates = array_keys($days);
            $holidays = Holiday::whereIn('date', $all_dates)->get();
            foreach($holidays as $h) {
                if ($include_holidays == false) {
                    unset($days[$h->date]);
                }
                else {
                    $days[$h->date]->holiday = $h;
                }
            }
        }

        ksort($days);
        return $days;
    }

    public static function staticGetManualDays($days, $starts, $ends, $include_holidays)
    {
        $ret = [];

        foreach($days as $index => $date) {
            $holiday = Holiday::where('date', $date)->first();
            if ($include_holidays == false && $holiday != null) {
                continue;
            }

            $ret[$date] = (object)[
                'from' => $starts[$index],
                'to' => $ends[$index],
                'holiday' => $holiday
            ];
        }

        return $ret;
    }

    public function getDays($include_holidays = true)
    {
        if ($this->type == 'manual') {
            $days = array_map(function($i) {
                return $i->date;
            }, $this->recursion_obj->days);

            $starts = array_map(function($i) {
                return $i->from;
            }, $this->recursion_obj->days);

            $ends = array_map(function($i) {
                return $i->to;
            }, $this->recursion_obj->days);

            return self::staticGetManualDays($days, $starts, $ends, $include_holidays);
        }
        else {
            return self::staticGetDays($this->start, $this->end, $this->recursion_obj, $include_holidays);
        }
    }

    public function generateSlots($request = null)
    {
        $saved_slots = [];
        $days = $this->getDays(false);

        if ($request) {
            $to_restore = $request->input('to_restore', []);
        }
        else {
            $to_restore = [];
        }

        foreach($days as $d => $details) {
            $time_start = floatToTime($details->from);
            $time_end = floatToTime($details->to);

            $slot = $this->slots()->where('room_id', $this->room_id)->where('date', $d)->where('from', $time_start)->where('to', $time_end)->first();
            if (is_null($slot)) {
                $slot = new Slot();
                $slot->booking_id = $this->id;
                $slot->room_id = $this->room_id;
                $slot->date = $d;
                $slot->from = $time_start;
                $slot->to = $time_end;
                $slot->save();
            }
            else {
                if ($slot->abolished && in_array($slot->id, $to_restore)) {
                    $slot->abolished = false;
                    $slot->save();
                }
            }

            $existing = $slot->getOverlapping();
            if($existing) {
                $action = $request->input('keepers_' . $existing->id);
                if ($action == 'keep') {
                    $slot->abolished = true;
                    $existing->abolished = false;
                }
                else if ($action == 'replace') {
                    $slot->abolished = false;
                    $existing->abolished = true;
                }
                else {
                    Log::error('Unable to determine conflicting status between slots');
                    throw new \Exception("Conflitto non risolto con prenotazione già esistente", 1);
                }

                $slot->save();
                $existing->save();
            }

            $saved_slots[] = $slot->id;
        }

        $this->slots()->whereNotIn('id', $saved_slots)->delete();
    }

    public function getYearHumanSummaryAttribute()
    {
        $days_names = days();
        $info = $this->recursion_obj;

        $ret = [];

        foreach($info->cycle as $cycle) {
            $cycle_prefix = '';

            switch($cycle) {
                case 'all':

app/Slot.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Events\SluggableCreating;

class Slot extends Model
{
    use SluggableID;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $dispatchesEvents = [
        'creating' => SluggableCreating::class,
    ];

    public function booking()
    {
        return $this->belongsTo('App\Booking');
    }

    public function room()
    {
        return $this->belongsTo('App\Room');
    }

    public function getGridClassAttribute()
    {
        return sprintf('event-%s %s', $this->booking->type, $this->booking->color);
    }

    public function getDurationCellsAttribute()
    {
        return ((timeToFloat($this->to) - timeToFloat($this->from)) * 2);
    }

    public static function getStaticOverlapping($booking_id, $room_id, $date, $time_start, $time_end)
    {
        return Slot::where('booking_id', '!=', $booking_id)->where('abolished', false)->where('room_id', $room_id)->where('date', $date)->where(function($query) use ($time_start, $time_end) {
            $query->where(function($subquery) use ($time_start, $time_end) {
                $subquery->where('from', '>=', $time_start)->where('from', '<', $time_end);
            })->orWhere(function($subquery) use ($time_start, $time_end) {
                $subquery->where('to', '>', $time_start)->where('to', '<=', $time_end);
            });
        })->first();
    }

    public function getOverlapping()
    {
        return self::getStaticOverlapping($this->booking_id, $this->room_id, $this->date, $this->from, $this->to);
    }

    /************************************************************ SluggableID */

    public function getSluggableID()
    {
        return sprintf('%s %s %s %s %s', $this->booking->name, $this->room->name, $this->date, $this->from, $this->to);
    }
}

resources/views/day.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.menu', ['active' => 'home', 'mode' => 'day'])

    @if($rooms->count() == 0)
        <h2 class="ui center aligned icon header">
            <i class="circular settings icon"></i>
            Per iniziare, crea almeno una sala.
        </h2>
    @else
        <?php

        $column_size = 92 / $rooms->count();
        $is_holiday = (App\Holiday::where('date', $day)->first() != null);

        ?>

        <div class="print-only">
            <h2>{{ fullDate($day) }}</h2>
        </div>

        <div class="freeze-table">
            <table class="ui selectable structured table fixed celled main-grid">
                <thead>
                    <tr>
                        <th width="8%">
                            <div class="ui icon top left pointing dropdown button no-print" id="room-column-selector">
                                <i class="wrench icon"></i>
                                <div class="menu">
                                    @foreach($rooms as $room)
                                        <div class="item">
                                            <div class="ui toggle checkbox">
                                                <input type="checkbox" value="{{ $room->id }}">
                                                <label>{{ $room->name }}</label>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </th>

                        @foreach($rooms as $room)
                            <th class="{{ $is_holiday ? 'holiday' : '' }}" width="{{ $column_size }}%" data-room-id="{{ $room->id }}" data-columner-target="{{ $room->id }}">{{ $room->name }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @include('booking.gridday', ['day' => $day, 'show_day' => false, 'rooms' => $rooms])
                </tbody>
            </table>
        </div>
    @endif
@endsection

resources/views/room.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.menu', ['active' => 'home', 'mode' => 'room'])

    @if($rooms->count() == 0)
        <h2 class="ui center aligned icon header">
            <i class="circular settings icon"></i>
            Per iniziare, crea almeno una sala.
        </h2>
    @else
        <div class="print-only">
            <h2>{{ $room->name }}</h2>
        </div>

        <div class="freeze-table">
            <table class="ui selectable structured table fixed celled main-grid fixed-header">
                <thead>
                    @include('layouts.weekly_header', ['days' => $days, 'column_select' => true])
                </thead>
                <tbody>
                    @include('booking.gridroom', ['days' => $days, 'room' => $room])
                </tbody>
            </table>
        </div>
    @endif
@endsection

resources/views/weekly.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.menu', ['active' => 'home', 'mode' => 'weekly'])

    @if($rooms->count() == 0)
        <h2 class="ui center aligned icon header">
            <i class="circular settings icon"></i>
            Per iniziare, crea almeno una sala.
        </h2>
    @else
		@foreach($days as $index => $day)
            <h2 class="ui center aligned header">{{ $day->format('d/m') }}</h2>

            <table class="ui selectable structured table fixed celled main-grid compact hours_on_top">
                <thead>
                    <tr>
                        <td>&nbsp;</td>
                        @for($i = myConf('start_hour'); $i < myConf('end_hour'); $i += 0.5)
                            <td data-hour="{{ $i }}">{{ $t = floatToTime($i) }}</td>
                        @endfor
                    </tr>
                </thead>
                <tbody>
                    @foreach($rooms as $room)
                        <tr>
                            <td data-room-id="{{ $room->id }}">{{ $room->name }}</td>

                            @for($i = myConf('start_hour'); $i < myConf('end_hour'); $i += 0.5)
                                @if($slot = App\Slot::where('room_id', $room->id)->where('date', $day)->where('from', $t)->where('abolished', false)->first())
                                    @php
                                        $i += $slot->duration_cells;
                                    @endphp

                                    <td class="occupied" data-slot-url="{{ route('slot.edit', $slot->id) }}" rowspan="{{ $slot->duration_cells }}">
                                        <div class="{{ $slot->grid_class }}">
                                            <span class="grant-name">{{ $slot->booking->printable_description }}</span>
                                            <span class="customer-name">{{ $slot->booking->grant->customer->name }}</span>
                                        </div>
                                    </td>
                                @else
                                    <td data-day="{{ $day->format('Y-m-d') }}" data-hour="{{ $i }}">&nbsp;</td>
                                @endif
                            @endfor
                        </tr>
                    @endforeach
                </tbody>
            </table>

            @if($index != 0 && ($index + 1) % 4 == 0)
                <div class="page-break print-only"></div>
            @endif
		@endforeach
    @endif
@endsection