routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('booking/wizard/{page}', 'BookingController@wizard')->name('booking.wizard');
    Route::get('booking/askdestroy/{id}', 'BookingController@askdestroy')->name('booking.askdestroy');

    Route::get('room/equipment/{id}', 'RoomController@equipment')->name('room.equipment');

    Route::get('slot/askdestroy/{id}', 'SlotController@askdestroy')->name('slot.askdestroy');

    Route::get('grant/create/search_customer', 'GrantController@creatingByExistingCustomer')->name('grant.search_customer');
    Route::get('grant/create/new_customer', 'GrantController@creatingByNewCustomer')->name('grant.new_customer');
    Route::get('grant/document/{id}', 'GrantController@document')->name('grant.document');
    Route::get('grant/askdestroy/{id}', 'GrantController@askdestroy')->name('grant.askdestroy');

    Route::get('contact/askmasscreate', 'ContactController@askCSV')->name('contact.askmasscreate');
    Route::post('contact/masscreate', 'ContactController@importCSV')->name('contact.masscreate');
    Route::get('contact/search', 'ContactController@search')->name('contact.search');
    Route::get('contact/askdestroy/{id}', 'ContactController@askdestroy')->name('contact.askdestroy');

    Route::get('customer/search', 'CustomerController@search')->name('customer.search');
    Route::get('customer/contacts', 'CustomerController@contacts')->name('customer.contacts');
    Route::get('customer/askdestroy/{id}', 'CustomerController@askdestroy')->name('customer.askdestroy');

    Route::post('config/generic', 'ConfigController@generic')->name('config.generic');
    Route::post('config/users', 'ConfigController@users')->name('config.users');
    Route::post('config/equipments', 'ConfigController@equipments')->name('config.equipments');
    Route::post('config/review', 'ConfigController@review')->name('config.review');

    Route::resource('config', 'ConfigController');
    Route::resource('year', 'YearController');
    Route::resource('holiday', 'HolidayController');
    Route::resource('room', 'RoomController');
    Route::resource('customer', 'CustomerController');
    Route::resource('contact', 'ContactController');
    Route::resource('grant', 'GrantController');
    Route::resource('slot', 'SlotController');
    Route::resource('booking', 'BookingController');
});

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use DB;

use App\Customer;
use App\Grant;
use App\Year;
use App\Room;
use App\Booking;
use App\Payment;
use App\Holiday;

class BookingController extends Controller
{
    public function create(Request $request)
    {
        $grant = Grant::find($request->input('grant_id', -1));

        $selected_day = $request->input('day');
        $selected_room = $request->input('room');
        $selected_equipment = [];

        $selected_start_hour = $request->input('hour');
        $selected_end_hour = $selected_start_hour + 1;
        $selected_start_hour = floatToTime($selected_start_hour);
        if ($selected_end_hour > myConf('end_hour'))
            $selected_end_hour = $selected_start_hour + 0.5;
        $selected_end_hour = floatToTime($selected_end_hour);

        return view('booking.create', compact('grant', 'selected_room', 'selected_equipment', 'selected_day', 'selected_start_hour', 'selected_end_hour'));
    }

    private function buildPeriodInfo($request)
    {
        $type = $request->input('type');

        switch($type) {
            case 'recurring':
                $main_type = 'recurring';

                $days_in_week = $request->input('day');
                $from_hours = $request->input('from');
                $to_hours = $request->input('to');

                $cycle = $request->input('week_cycle');
                if ($cycle == 'none')
                    $cycle = $request->input('monthly_cycle');
                if (!is_array($cycle))
                    $cycle = [$cycle];

                $end_criteria = $request->input('end_criteria');
                $end = (object) [
                    'criteria' => $end_criteria
                ];

                switch($end_criteria) {
                    case 'all_year':
                        $end->yearly = 1;
                        break;
                    case 'given_day':
                        $end->date = $request->input('end_day');
                        break;
                    case 'given_number':
                        $end->number = $request->input('given_number_value');
                        break;
                }

                $days = [];

                foreach($days_in_week as $diw_index => $diw) {
                    if ($diw == -1)
                        continue;

                    $days[] = (object) [
                        'offset' => $diw,
                        'from' => $from_hours[$diw_index],
                        'to' => $to_hours[$diw_index],
                    ];
                }

                break;

            case 'occasional':
                $main_type = 'single';

                $cycle = ['all'];
                $start_date = readDate($request->input('start_day'));
                $end_date = readDate($request->input('end_day'));

                $end = (object) [
                    'criteria' => 'date',
                    'date' => $end_date
                ];

                $days = [];
                $all_days = new \DatePeriod(new \DateTime($start_date), new \DateInterval('P1D'), (new \DateTime($end_date))->modify('+1 days'));
                foreach($all_days as $d) {
                    $days[] = (object) [
                        'offset' => $d->format('w'),
                        'from' => $request->input('from'),
                        'to' => $request->input('to'),
                    ];
                }

                break;

            case 'manual':
                $main_type = 'manual';

                $cycle = ['manual'];

                $end = (object) [
                    'criteria' => 'manual'
                ];

                $ids = $request->input('choosen_day_id', []);
                $choosen_days = $request->input('choosen_days', []);
                $choosen_start = $request->input('from', []);
                $choosen_end = $request->input('to', []);
                $days = [];

                foreach($ids as $index => $id) {
                    if ($id != 'new') {
                        continue;
                    }

                    $days[] = (object) [
                        'date' => readDate($choosen_days[$index]),
                        'from' => $choosen_start[$index],
                        'to' => $choosen_end[$index]
                    ];
                }

                break;
        }

        $info = (object) [
            'type' => $main_type,
            'cycle' => $cycle,
            'end' => $end,
            'excluded' => $request->input('exclude_date', []),
            'days' => $days
        ];

        return $info;
    }

    private function buildDefaultPeriodInfo($request)
    {
        return (object) [
            'type' => 'recurring',
            'cycle' => ['all'],
            'end' => (object) [
                'criteria' => 'all_year',
            ],
            'excluded' => [],
            'days' => [
                (object) [
                    'offset' => -1,
                    'from' => $request->input('selected_start_hour'),
                    'to' => $request->input('selected_end_hour'),
                ]
            ]
        ];
    }

    private function buildDefaultManualPeriodInfo($request)
    {
        return (object) [
            'type' => 'manual',
            'cycle' => ['manual'],
            'end' => (object) [
                'criteria' => 'manual',
            ],
            'excluded' => [],
            'days' => [
                (object) [
                    'date' => $request->input('selected_day'),
                    'from' => $request->input('selected_start_hour'),
                    'to' => $request->input('selected_end_hour'),
                ]
            ]
        ];
    }

    private function getDaysRaw($request, $include_holidays = true)
    {
        $start = new \DateTime(readDate($request->input('start_day')));
        $info = self::buildPeriodInfo($request);
        $type = $request->input('type');

        switch($type) {
            case 'recurring':
                $end_criteria = $request->input('end_criteria');

                switch($end_criteria) {
                    case 'all_year':
                        $year = currentSocialYear();
                        $end = new \DateTime($year->end);
                        $days = Booking::staticGetDays($start, $end, $info, $include_holidays);
                        break;
                    case 'given_day':
                        $end = new \DateTime(readDate($request->input('end_day')));
                        $days = Booking::staticGetDays($start, $end, $info, $include_holidays);
                        break;
                    case 'given_number':
                        $days_number = $request->input('given_number_value');
                        if (is_numeric($days_number)) {
                            $end = clone $start;
                            $end->modify('+1 years');
                            $days = Booking::staticGetDays($start, $end, $info, $include_holidays);

                            $holidays_num = array_reduce($days, function($carry, $item) {
                                if (!is_null($item->holiday))
                                    return $carry + 1;
                                else
                                    return $carry;
                            }, 0);

                            $days = array_splice($days, 0, $days_number + $holidays_num);
                        }
                        else {
                            $days = [];
                        }

                        break;
                }

                break;

            case 'occasional':
                $end = new \DateTime(readDate($request->input('end_day')));
                $days = Booking::staticGetDays($start, $end, $info, $include_holidays);
                break;

            case 'manual':
                /*
                    Nella tabella dinamica coi giorni, per isolare le righe
                    buone da quella di riferimento viene aggiunto un ID
                    farlocco. Quelle buone hanno ID = 'new', in quella di
                    riferimento ne viene settato uno farlocco per identificarla
                    e saltarla
                */
                $ids = $request->input('choosen_day_id', []);
                $choosen_days = $request->input('choosen_days', []);
                $choosen_start = $request->input('from', []);
                $choosen_end = $request->input('to', []);
                $days = [];
                $starts = [];
                $ends = [];

                foreach($ids as $index => $id) {
                    if ($id != 'new') {
                        continue;
                    }

                    $days[] = readDate($choosen_days[$index]);
                    $starts[] = $choosen_start[$index];
                    $ends[] = $choosen_end[$index];
                }

                $days = Booking::staticGetManualDays($days, $starts, $ends, $include_holidays);
                break;
        }

        return $days;
    }

    public function wizard(Request $request, $page)
    {
        switch ($page) {
            case 'search_customer':
                return view('booking.customers.search');

            case 'new_customer':
                return view('booking.customers.new');

            case 'customers':
                $customer_id = $request->input('customer_id');
                if (empty($customer_id) || $customer_id == 'new')
                    $customer = new Customer();
                else
                    $customer = Customer::find($customer_id);

                return view('booking.customers.grants', compact('customer'));
                break;

            case 'spaces':
                $type = $request->input('type');

                switch($type) {
                    case 'recurring':

resources/views/booking/askdestroy.blade.php
<div class="ui mini modal">
    <i class="close icon"></i>
    <div class="header">
        Elimina Prenotazione
    </div>
    <div class="content">
        <p>
            Sei sicuro di voler eliminare la prenotazione di {{ $booking->grant->customer->name }}?
        </p>

        <form method="POST" action="{{ route('booking.destroy', $booking->id) }}" class="ui form">
            @csrf
            @method('DELETE')
            <input type="hidden" name="mode" value="all">
            <button class="ui negative button" type="submit">Elimina Tutto</button>
            <p>
                Elimina la prenotazione e tutte le relative occupazioni della sala.
            </p>
        </form>

        @if($booking->slots()->where('date', '>', date('Y-m-d'))->count() > 0)
            <div class="ui divider"></div>

            <form method="POST" action="{{ route('booking.destroy', $booking->id) }}" class="ui form">
                @csrf
                @method('DELETE')
                <input type="hidden" name="mode" value="partial">
                <button class="ui negative button" type="submit">Annulla Prenotazione</button>
                <p>
                    Annulla l'occupazione della sala a partire da domani, la prenotazione si conclude oggi.
                </p>
            </form>
        @endif
    </div>
</div>

resources/views/booking/create.blade.php
<div class="ui large modal creating-booking">
    <i class="close icon"></i>
    <div class="header">
        Crea Prenotazione
    </div>
    <div class="scrolling content">
        <form method="POST" action="{{ route('booking.store') }}" class="ui form">
            @csrf

            <input type="hidden" name="selected_room" value="{{ $selected_room }}">
            <input type="hidden" name="selected_day" value="{{ $selected_day }}">
            <input type="hidden" name="selected_start_hour" value="{{ $selected_start_hour }}">
            <input type="hidden" name="selected_end_hour" value="{{ $selected_end_hour }}">

            <div class="wizard">
                <div class="ui three top attached steps">
                    <div class="active step">
                        <div class="content">
                            <div class="title">Chi</div>
                        </div>
                    </div>
                    <div class="step">
                        <div class="content">
                            <div class="title">Quando</div>
                        </div>
                    </div>
                    <div class="step">
                        <div class="content">
                            <div class="title">Quanto</div>
                        </div>
                    </div>
                </div>

                <div class="ui attached segment">
                    <div class="wizard-step active" id="first_step_booking">
                        @if($grant == null)
                            <div class="field">
                                <label>Cliente</label>
                                @include('booking.customers.search', ['can_create_on' => 'first_step_booking'])
                            </div>
                        @else
                            <div class="field ui search customer_complete">
                                <label>Cliente</label>
                                <p>{{ $grant->customer->name }}</p>
                            </div>

                            @include('grant.embed_ro', ['grant' => $grant])
                        @endif
                    </div>

                    <div class="wizard-step">
                        <div class="three fields">
                            <div class="field">
                                <label>Descrizione</label>
                                <input type="text" name="description" value="">
                            </div>

                            <div class="field">
                                <label>Colore</label>
                                <input type="text" class="color" name="color" value="red">
                            </div>

                            <div class="required field">
                                <label>Tipo</label>
                                <div class="inline fields radio-loader" data-load-url="{{ route('booking.wizard', ['page' => 'spaces']) }}" data-load-area=".booking_spaces">
                                    <div class="field">
                                        <div class="ui radio checkbox">
                                            <input type="radio" name="type" value="recurring" class="hidden" required>
                                            <label>Ricorrente</label>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="ui radio checkbox checked">
                                            <input type="radio" name="type" value="occasional" class="hidden" checked required>
                                            <label>Occasionale</label>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="ui radio checkbox">
                                            <input type="radio" name="type" value="manual" class="hidden" required>
                                            <label>Manuale</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <br>

                        <div class="booking_spaces">
                            @include('booking.spaces.single', compact('selected_room', 'selected_equipment', 'selected_day', 'selected_start_hour', 'selected_end_hour'))
                        </div>
                    </div>

                    <div class="wizard-step payments-wrapper">
                        <div class="field">
                            <label>Numero Partecipanti</label>
                            <input type="number" name="partecipants" value="0">
                        </div>

                        <div class="field">
                            <label>Pagamento</label>
                            <div class="grouped fields radio-loader" data-load-url="{{ route('booking.wizard', ['page' => 'payments']) }}" data-load-area=".booking_payments">
                                <div class="field">
                                    <div class="ui radio checkbox">
                                        <input type="radio" name="payment" value="pay" class="hidden">
                                        <label>A Pagamento</label>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="ui radio checkbox">
                                        <input type="radio" name="payment" value="free" class="hidden" checked>
                                        <label>Gratuito</label>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="ui radio checkbox">
                                        <input type="radio" name="payment" value="contribute" class="hidden">
                                        <label>Contributo</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="booking_payments">
                            @include('booking.payments.free')
                        </div>

                        @include('booking.payments.deposit', ['booking' => null])
                    </div>
                </div>

                <div class="ui basic right floated segment wizard-actions">
                    <button class="ui button wizard-prev">Indietro</button>
                    <button class="ui button wizard-next">Avanti</button>
                    <button class="ui green button wizard-finish">Salva</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/booking/edit.blade.php
<div class="ui large modal">
    <i class="close icon"></i>
    <div class="header">
        Modifica Prenotazione
    </div>
    <div class="scrolling content">
        <form method="POST" action="{{ route('booking.update', $booking->id) }}" class="ui form">
            @csrf
            @method('PUT')

            <input type="hidden" name="booking_id" value="{{ $booking->id }}">
            <input type="hidden" name="selected_room" value="{{ $booking->room_id }}">
            @foreach($booking->equipments as $eq)
                <input type="hidden" name="selected_equipment[]" value="{{ $eq->id }}">
            @endforeach
            <input type="hidden" name="selected_day" value="{{ $booking->start }}">
            <input type="hidden" name="selected_start_hour" value="{{ floatToTime($booking->recursion_obj->days[0]->from) }}">
            <input type="hidden" name="selected_end_hour" value="{{ floatToTime($booking->recursion_obj->days[0]->to) }}">

            <div class="ui top attached tabular menu booking-wizard">
                <div class="item active" data-tab="customers">Chi</div>
                <div class="item" data-tab="spaces">Quando</div>
                <div class="item" data-tab="payments">Quanto</div>
            </div>

            <div class="ui bottom attached tab segment active" data-tab="customers">
                <div class="field ui search customer_complete">
                    <label>Cliente</label>
                    <p>{{ $booking->grant->customer->name }}</p>
                </div>

                @include('grant.embed_ro', ['grant' => $booking->grant])
            </div>

            <div class="ui bottom attached tab segment" data-tab="spaces">
                <div class="three fields">
                    <div class="field">
                        <label>Descrizione</label>
                        <input type="text" name="description" value="{{ $booking->description }}">
                    </div>

                    <div class="field">
                        <label>Colore</label>
                        <input type="text" class="color" name="color" value="{{ $booking->color }}">
                    </div>

                    <div class="required field">
                        <label>Tipo</label>
                        <div class="inline fields radio-loader" data-load-url="{{ route('booking.wizard', ['page' => 'spaces']) }}" data-load-area=".booking_spaces">
                            <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="type" value="recurring" class="hidden" required {{ $booking->type == 'recurring' ? 'checked' : '' }}>
                                    <label>Ricorrente</label>
                                </div>
                            </div>
                            <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="type" value="occasional" class="hidden" required {{ $booking->type == 'occasional' ? 'checked' : '' }}>
                                    <label>Occasionale</label>
                                </div>
                            </div>
                            <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="type" value="manual" class="hidden" required {{ $booking->type == 'manual' ? 'checked' : '' }}>
                                    <label>Manuale</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <br>

                <div class="booking_spaces">
                    @if($booking->type == 'occasional')
                        @include('booking.spaces.single', [
                            'selected_room' => $booking->room_id,
                            'selected_equipment' => $booking->equipments->pluck('id')->toArray(),
                            'selected_day' => $booking->start,
                            'selected_end_day' => $booking->end,
                            'selected_start_hour' => floatToTime($booking->recursion_obj->days[0]->from),
                            'selected_end_hour' => floatToTime($booking->recursion_obj->days[0]->to)
                        ])
                    @elseif($booking->type == 'recurring')
                        @include('booking.spaces.recurring', [
                            'selected_room' => $booking->room_id,
                            'selected_equipment' => $booking->equipments->pluck('id')->toArray(),
                            'selected_day' => $booking->start,
                            'details' => $booking->recursion_obj
                        ])
                    @elseif($booking->type == 'manual')
                        @include('booking.spaces.manual', [
                            'selected_room' => $booking->room_id,
                            'selected_equipment' => $booking->equipments->pluck('id')->toArray(),
                            'details' => $booking->recursion_obj
                        ])
                    @endif
                </div>
            </div>

            <div class="ui bottom attached tab segment payments-wrapper" data-tab="payments">
                <div class="field">
                    <label>Numero Partecipanti</label>
                    <input type="number" name="partecipants" value="{{ $booking->partecipants }}">
                </div>

                <div class="field">
                    <label>Pagamento</label>
                    <div class="grouped fields radio-loader" data-load-url="{{ route('booking.wizard', ['page' => 'payments']) }}" data-load-area=".booking_payments">
                        <div class="field">
                            <div class="ui radio checkbox">
                                <input type="radio" name="payment" value="pay" class="hidden" required {{ $booking->payment == 'pay' ? 'checked' : '' }}>
                                <label>A Pagamento</label>
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui radio checkbox">
                                <input type="radio" name="payment" value="free" class="hidden" required {{ $booking->payment == 'free' ? 'checked' : '' }}>
                                <label>Gratuito</label>
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui radio checkbox">
                                <input type="radio" name="payment" value="contribute" class="hidden" required {{ $booking->payment == 'contribute' ? 'checked' : '' }}>
                                <label>Contributo</label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="booking_payments">
                    <?php $involved_days = $booking->getDays(false) ?>
                    @if($booking->payment == 'pay')
                        @include('booking.payments.full', [
                            'days' => $involved_days,
                            'unit_price' => $booking->unit_price,
                            'total_price' => $booking->total_price,
                            'payments' => $booking->payments,
                        ])
                    @elseif($booking->payment == 'free')
                        @include('booking.payments.free')
                    @elseif($booking->payment == 'contribute')
                        @include('booking.payments.single', [
                            'days' => $involved_days,
                            'unit_price' => $booking->unit_price,
                            'total_price' => $booking->total_price,
                            'payment' => $booking->payments->first(),
                        ])
                    @endif
                </div>

                @include('booking.payments.deposit', ['booking' => $booking])
            </div>

            <button class="ui positive button" type="submit">Salva</button>
            <a class="ui negative button right floated async-modal" href="#" data-modal-url="{{ route('booking.askdestroy', $booking->id) }}">Elimina o Annulla</a>
        </form>
    </div>
</div>

resources/views/booking/gridday.blade.php
<?php

$column_num = $rooms->count() + 1;

$filled = [];
foreach($rooms as $room) {
    $filled[$room->id] = [];
    for($i = myConf('start_hour'); $i < myConf('end_hour'); $i += 0.5)
        $filled[$room->id][(string) $i] = false;
}

?>

@if($show_day)
    <tr>
        <td class="day-separator" colspan="{{ $column_num }}" data-day="{{ $day->format('Y-m-d') }}">{{ $day->format('l d/m') }}</td>
    </tr>
@endif

@for($i = myConf('start_hour'); $i < myConf('end_hour'); $i += 0.5)
    <tr>
        <td data-hour="{{ $i }}">{{ $t = floatToTime($i) }}</td>

        @foreach($rooms as $room)
            @if($filled[$room->id][(string) $i])
                @continue
            @endif

            @if($slot = App\Slot::where('room_id', $room->id)->where('date', $day)->where('from', $t)->where('abolished', false)->first())
                @php
                    $duration = $slot->duration_cells;
                    for($void = $i; $void < ($i + ($duration / 2)); $void += 0.5)
                        $filled[$room->id][(string) $void] = true;
                @endphp

                @include('slot.cell', ['slot' => $slot])
            @else
                <td data-room-id="{{ $room->id }}">&nbsp;</td>
            @endif
        @endforeach
    </tr>
@endfor