routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('booking/wizard/{page}', 'BookingController@wizard')->name('booking.wizard');
    Route::get('booking/askdestroy/{id}', 'BookingController@askdestroy')->name('booking.askdestroy');

    Route::get('room/equipment/{id}', 'RoomController@equipment')->name('room.equipment');

    Route::get('slot/askdestroy/{id}', 'SlotController@askdestroy')->name('slot.askdestroy');

    Route::get('grant/create/search_customer', 'GrantController@creatingByExistingCustomer')->name('grant.search_customer');
    Route::get('grant/create/new_customer', 'GrantController@creatingByNewCustomer')->name('grant.new_customer');
    Route::get('grant/document/{id}', 'GrantController@document')->name('grant.document');
    Route::get('grant/askdestroy/{id}', 'GrantController@askdestroy')->name('grant.askdestroy');

    Route::get('contact/askmasscreate', 'ContactController@askCSV')->name('contact.askmasscreate');
    Route::post('contact/masscreate', 'ContactController@importCSV')->name('contact.masscreate');
    Route::get('contact/search', 'ContactController@search')->name('contact.search');
    Route::get('contact/askdestroy/{id}', 'ContactController@askdestroy')->name('contact.askdestroy');

    Route::get('customer/search', 'CustomerController@search')->name('customer.search');
    Route::get('customer/contacts', 'CustomerController@contacts')->name('customer.contacts');
    Route::get('customer/askdestroy/{id}', 'CustomerController@askdestroy')->name('customer.askdestroy');

    Route::post('config/generic', 'ConfigController@generic')->name('config.generic');
    Route::post('config/users', 'ConfigController@users')->name('config.users');
    Route::post('config/equipments', 'ConfigController@equipments')->name('config.equipments');
    Route::post('config/review', 'ConfigController@review')->name('config.review');

    Route::resource('config', 'ConfigController');
    Route::resource('year', 'YearController');
    Route::resource('holiday', 'HolidayController');
    Route::resource('room', 'RoomController');
    Route::resource('customer', 'CustomerController');
    Route::resource('contact', 'ContactController');
    Route::resource('grant', 'GrantController');
    Route::resource('slot', 'SlotController');
    Route::resource('booking', 'BookingController');
});

app/Config.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Log;

class Config extends Model
{
    public static function provideDefault($name)
    {
        $defaults = [
            'start_hour' => 8,
            'end_hour' => 24
        ];

        if (isset($defaults[$name])) {
            $c = new Config();
            $c->name = $name;
            $c->value = $defaults[$name];
            $c->save();
            return $c;
        }
        else {
            Log::error('Configuration type not found: ' . $name);
            return null;
        }
    }
}

app/Http/Controllers/ConfigController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

use Hash;

use App\Config;
use App\User;
use App\Room;
use App\Equipment;
use App\Slot;
use App\Booking;
use App\Payment;
use App\Holiday;

class ConfigController extends Controller
{
    public function index(Request $request)
    {
        if ($request->user()->role != 'admin')
            abort(403);

        return view('config.index');
    }

    public function generic(Request $request)
    {
        if ($request->user()->role != 'admin')
            abort(403);

        $config = Config::where('name', 'start_hour')->first();
        $config->value = $request->input('start_hour');
        $config->save();

        $config = Config::where('name', 'end_hour')->first();
        $config->value = $request->input('end_hour');
        $config->save();

        return redirect()->route('config.index');
    }

    public function users(Request $request)
    {
        if ($request->user()->role != 'admin')
            abort(403);

        $ids = $request->input('id');
        $names = $request->input('name');
        $emails = $request->input('email');
        $passwords = $request->input('password');
        $admins = $request->input('admin');

        $rooms = [];
        foreach(Room::all() as $room) {
            $rooms[$room->id] = $request->input('room_' . $room->id);
        }

        $saved = [];

        foreach($ids as $index => $id) {
            if ($id == 'empty') {
                continue;
            }
            else if ($id == 'new') {
                $user = new User();
            }
            else {
                $user = User::find($id);
            }

            if (empty($emails[$index]))
                continue;

            $user->name = $names[$index];
            $user->email = $emails[$index];

            if (!empty($passwords[$index]))
                $user->password = Hash::make($passwords[$index]);
            else if ($id == 'new')
                $user->password = Hash::make(Str::random(10));

            if ($admins[$index] == 1)
                $user->role = 'admin';
            else
                $user->role = 'manager';

            $user->save();

            $assigned_rooms = [];
            foreach($rooms as $room_id => $assignations) {
                if ($assignations[$index] == 1)
                    $assigned_rooms[] = $room_id;
            }
            $user->rooms()->sync($assigned_rooms);

            $saved[] = $user->id;
        }

        User::whereNotIn('id', $saved)->delete();

        return redirect()->route('config.index');
    }

    public function equipments(Request $request)
    {
        if ($request->user()->role != 'admin')
            abort(403);

        $ids = $request->input('id');
        $names = $request->input('name');

        $saved = [];

        foreach($ids as $index => $id) {
            if ($id == 'empty') {
                continue;
            }
            else if ($id == 'new') {
                $equipment = new Equipment();
            }
            else {
                $equipment = Equipment::find($id);
            }

            $name = $names[$index];
            if (empty(trim($name))) {
                continue;
            }

            $equipment->name = $names[$index];
            $equipment->save();

            $saved[] = $equipment->id;
        }

        Equipment::whereNotIn('id', $saved)->delete();

        return redirect()->route('config.index');
    }

    public function review()
    {
        $holiday_dates = Holiday::select('date')->get()->pluck('date');
        $booking_ids = Slot::select('booking_id')->distinct()->whereIn('date', $holiday_dates)->pluck('booking_id');
        Slot::select('booking_id')->distinct()->whereIn('date', $holiday_dates)->delete();
        $bookings = Booking::whereIn('id', $booking_ids)->where('payment', 'pay')->get();

        $qs = ['first', 'second', 'third', 'fourth'];

        foreach($bookings as $booking) {
            $days = $booking->getDays(false);
            $quarters = Booking::sortDaysByQuarter($days);

            foreach($qs as $q)
                Payment::where('booking_id', $booking->id)->where('payed', false)->where('quarter', $q)->update(['amount' => $quarters->$q->days * $booking->unit_price]);
        }

        return redirect()->route('config.index');
    }
}

resources/views/config/index.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.menu', ['active' => 'config'])

    <div class="ui grid container">
        <?php

        $holiday_dates = App\Holiday::select('date')->get()->pluck('date');
        $overlapping_count = App\Slot::whereIn('date', $holiday_dates)->count();

        ?>

        @if($overlapping_count != 0)
            <div class="sixteen wide column">
                <div class="ui negative message">
                    <p>
                        Attenzione! Ci sono prenotazioni che includono giorni di chiusura! Cliccando il tasto sotto gli slot nei giorni di chiusura verranno eliminati e saranno ricalcolati i pagamenti (non ancora pagati) delle relative prenotazioni.
                    </p>
                    <form method="POST" action="{{ route('config.review') }}">
                        @csrf
                        <button type="submit" class="ui red button">Elimina slot e ricalcola pagamenti</button>
                    </form>
                </div>
            </div>
        @endif

        <div class="sixteen wide column">
            <h3 class="ui top attached header">
                Configurazioni Globali
            </h3>
            <div class="ui attached segment">
                <form method="POST" action="{{ route('config.generic') }}" class="ui form">
                    @csrf

                    <div class="two fields">
                        <div class="field">
                            <label>Ora Inizio</label>
                            <input type="number" name="start_hour" value="{{ myConf('start_hour') }}">
                        </div>
                        <div class="field">
                            <label>Ora Fine</label>
                            <input type="number" name="end_hour" value="{{ myConf('end_hour') }}">
                        </div>
                    </div>

                    <button class="ui positive button" type="submit">Salva</button>
                </form>
            </div>

            <h3 class="ui top attached header">
                Anni Sociali
            </h3>
            <div class="ui attached segment">
                <table id="years" class="ui basic table">
                    <thead>
                        <tr>
                            <th width="30%">Anno</th>
                            <th width="30%">Inizio</th>
                            <th width="30%">Fine</th>
                            <th width="10%">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(App\Year::orderBy('name', 'desc')->get() as $year)
                            <tr>
                                <td>{{ $year->name }}</td>
                                <td>{{ fullDate($year->start) }}</td>
                                <td>{{ fullDate($year->end) }}</td>
                                <td>
                                    <button class="ui blue icon button async-modal" data-modal-url="{{ route('year.edit', $year->id) }}"><i class="zoom in icon"></i></button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>
                                <button class="ui orange basic button async-modal" data-modal-url="{{ route('year.create') }}">Aggiungi Anno</button>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>

            <h3 class="ui top attached header">
                Utenti
            </h3>
            <div class="ui attached segment">
                <form method="POST" action="{{ route('config.users') }}" class="ui form">
                    @csrf

                    <table id="rooms" class="ui very basic table dynamic-table">
                        <thead>
                            <tr>
                                <th width="20%">Nome</th>
                                <th width="20%">E-Mail</th>
                                <th width="20%">Password<br>(lascia in bianco per non modificare)</th>
                                <th width="30%">Sale Gestite</th>
                                <th width="5%">Amministratore</th>
                                <th width="5%">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(App\User::orderBy('name', 'asc')->get() as $user)
                                @include('user.edit', ['user' => $user])
                            @endforeach

                            @include('user.edit', ['user' => null])
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="2">
                                    <button class="ui orange basic button add-row">Aggiungi Utente</button>
                                </td>
                            </tr>
                        </tfoot>
                    </table>

                    <button class="ui positive button" type="submit">Salva</button>
                </form>
            </div>

            <h3 class="ui top attached header">
                Attrezzature
            </h3>
            <div class="ui attached segment">
                <form method="POST" action="{{ route('config.equipments') }}" class="ui form">
                    @csrf

                    <table id="equipments" class="ui basic table dynamic-table">
                        <thead>
                            <tr>
                                <th width="95%">Nome</th>
                                <th width="5%">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(App\Equipment::orderBy('name', 'asc')->get() as $equipment)
                                @include('equipment.edit', ['equipment' => $equipment])
                            @endforeach

                            @include('equipment.edit', ['equipment' => null])
                        </tbody>
                        <tfoot>
                            <tr>
                                <td>
                                    <button class="ui orange basic button add-row" data-table-target="#equipments">Aggiungi Attrezzatura</button>
                                </td>
                            </tr>
                        </tfoot>
                    </table>

                    <div class="ui divider"></div>

                    <button class="ui positive button" type="submit">Salva</button>
                </form>
            </div>
        </div>
    </div>
@endsection