routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('booking/wizard/{page}', 'BookingController@wizard')->name('booking.wizard');
    Route::get('booking/askdestroy/{id}', 'BookingController@askdestroy')->name('booking.askdestroy');

    Route::get('room/equipment/{id}', 'RoomController@equipment')->name('room.equipment');

    Route::get('slot/askdestroy/{id}', 'SlotController@askdestroy')->name('slot.askdestroy');

    Route::get('grant/create/search_customer', 'GrantController@creatingByExistingCustomer')->name('grant.search_customer');
    Route::get('grant/create/new_customer', 'GrantController@creatingByNewCustomer')->name('grant.new_customer');
    Route::get('grant/document/{id}', 'GrantController@document')->name('grant.document');
    Route::get('grant/askdestroy/{id}', 'GrantController@askdestroy')->name('grant.askdestroy');

    Route::get('contact/askmasscreate', 'ContactController@askCSV')->name('contact.askmasscreate');
    Route::post('contact/masscreate', 'ContactController@importCSV')->name('contact.masscreate');
    Route::get('contact/search', 'ContactController@search')->name('contact.search');
    Route::get('contact/askdestroy/{id}', 'ContactController@askdestroy')->name('contact.askdestroy');

    Route::get('customer/search', 'CustomerController@search')->name('customer.search');
    Route::get('customer/contacts', 'CustomerController@contacts')->name('customer.contacts');
    Route::get('customer/askdestroy/{id}', 'CustomerController@askdestroy')->name('customer.askdestroy');

    Route::post('config/generic', 'ConfigController@generic')->name('config.generic');
    Route::post('config/users', 'ConfigController@users')->name('config.users');
    Route::post('config/equipments', 'ConfigController@equipments')->name('config.equipments');
    Route::post('config/review', 'ConfigController@review')->name('config.review');

    Route::resource('config', 'ConfigController');
    Route::resource('year', 'YearController');
    Route::resource('holiday', 'HolidayController');
    Route::resource('room', 'RoomController');
    Route::resource('customer', 'CustomerController');
    Route::resource('contact', 'ContactController');
    Route::resource('grant', 'GrantController');
    Route::resource('slot', 'SlotController');
    Route::resource('booking', 'BookingController');
});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Events\SluggableCreating;

class Customer extends Model
{
    use SluggableID;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $dispatchesEvents = [
        'creating' => SluggableCreating::class,
    ];

    public function grants()
    {
        return $this->hasMany('App\Grant')->orderBy('year', 'desc');
    }

    public function contacts()
    {
        return $this->belongsToMany('App\Contact')->orderBy('name', 'asc');
    }

    public function scopeRecent($query)
    {
        $query->whereHas('grants', function($query) {
            $query->whereHas('bookings', function($query) {
                $query->where('end', '>=', date('Y-m-d', strtotime('-1 years')));
            });
        });
    }

    public function readRequest($request, $prefix = '')
    {
        $this->name = $request->input($prefix . 'name');
        $this->type = $request->input($prefix . 'type');
        $this->address = $request->input($prefix . 'address');
        $this->city = $request->input($prefix . 'city');
        $this->zip = $request->input($prefix . 'zip');
        $this->vat = $request->input($prefix . 'vat');
        $this->taxcode = $request->input($prefix . 'taxcode');
        $this->phone = $request->input($prefix . 'phone');
        $this->email = $request->input($prefix . 'email');
        $this->website = $request->input($prefix . 'website');
        $this->discount = $request->input($prefix . 'discount', 0);
        $this->notes = $request->input($prefix . 'notes');
    }

    public function readContacts($request, $field = 'contact_id')
    {
        $ids = array_filter($request->input($field));

        $ids = array_filter($ids, function($item) {
            return $item != 'new';
        });

        $this->contacts()->sync($ids);
    }
}

app/CustomerType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Events\SluggableCreating;

class CustomerType extends Model
{
    use SluggableID;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $dispatchesEvents = [
        'creating' => SluggableCreating::class,
    ];
}

app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Events\SluggableCreating;

use App\Booking;

class Payment extends Model
{
    use SluggableID;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $dispatchesEvents = [
        'creating' => SluggableCreating::class,
    ];

    public function booking()
    {
        return $this->belongsTo('App\Booking');
    }

    public function getQuarterDaysAttribute()
    {
        if ($this->quarter == 'none')
            return 0;

        $q = $this->quarter;
        $quarters = Booking::sortDaysByQuarter($this->booking->getDays(false));
        return $quarters->$q->days;
    }

    public function getPrintableFullDescriptionAttribute()
    {
        if ($this->payed)
            $status = 'green';
        else if ($this->date < date('Y-m-d'))
            $status = 'red';
        else
            $status = 'orange';

        return sprintf('<div class="ui %s horizontal label">%s - %s - %s€</div>', $status, $this->description, writeDate($this->date), $this->amount);
    }

    public static function saveBatch($request, $booking = null)
    {
        $payments = $request->input('payment_id');
        $payments_description = $request->input('payment_description');
        $payments_quarter = $request->input('payment_quarter');
        $payments_amount = $request->input('payment_amount');
        $payments_date = $request->input('payment_date');
        $payments_payed = $request->input('payment_payed');

        if ($payments) {
            foreach($payments as $index => $payment) {
                if (empty($payment) || $payment == 'empty') {
                    $pay = new Payment();
                    $pay->booking_id = $booking->id;
                }
                else {
                    $pay = Payment::find($payment);
                }

                if ($pay == null) {
                    $pay = new Payment();
                    $pay->booking_id = $booking->id;
                    if (!empty($payment) && $payment != 'empty')
                        $pay->id = $payment;
                }

                $amount = $payments_amount[$index];

                if ($amount == 0) {
                    if ($pay->exists)
                        $pay->delete();
                    continue;
                }

                $pay->description = $payments_description[$index];
                $pay->quarter = $payments_quarter[$index];
                $pay->amount = $amount;
                $pay->date = readDate($payments_date[$index]);
                $pay->payed = $payments_payed[$index];
                $pay->save();
            }
        }
    }

    /************************************************************ SluggableID */

    public function getSluggableID()
    {
        return sprintf('%s %s', $this->booking->grant->description, $this->date);
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Customer;
use App\Contact;
use App\Grant;

class CustomerController extends Controller
{
    public function index(Request $request)
    {
        $display = $request->input('display', 'recent');

        if ($display == 'all') {
            $customers = Customer::orderBy('name', 'asc')->get();
        }
        else {
            $customers = Customer::orderBy('name', 'asc')->recent()->get();
        }

        return view('customer.index', compact('customers', 'display'));
    }

    public function search(Request $request)
    {
        $search = $request->input('search');
        $ret = (object) [
            'results' => []
        ];

        $query = Customer::where('name', 'like', "%$search%");

        if ($request->has('exclude') && !empty($request->input('exclude')))
            $query->where('id', '!=', $request->input('exclude'));

        $customers = $query->get();

        foreach($customers as $customer) {
            $ret->results[] = (object) [
                'title' => $customer->name,
                'id' => $customer->id,
            ];
        }

        return response()->json($ret);
    }

    private function readGrants($customer, $request)
    {
        $ids = $request->input('grant_id');
        $saved = [];

        if (is_array($ids)) {
            foreach($ids as $index => $id) {
                if (empty($id)) {
                    continue;
                }

                $saved[] = $id;
            }
        }

        Grant::where('customer_id', $customer->id)->whereNotIn('id', $saved)->delete();
    }

    public function create(Request $request)
    {
        $customer = null;
        return view('customer.edit', compact('customer'));
    }

    public function store(Request $request)
    {
        $customer = new Customer();
        $customer->readRequest($request);
        $customer->save();
        $customer->readContacts($request, 'contact_id');
        return redirect()->route('customer.index');
    }

    public function edit($id)
    {
        $customer = Customer::find($id);
        return view('customer.edit', compact('customer'));
    }

    public function update(Request $request, $id)
    {
        $customer = Customer::find($id);
        $customer->readRequest($request);
        $customer->save();
        $customer->readContacts($request, 'contact_id');
        self::readGrants($customer, $request);
        return redirect()->route('customer.index');
    }

    public function contacts(Request $request)
    {
        $id = $request->input('customer_id');
        $customer = Customer::find($id);
        return view('customer.contactselect', compact('customer'));
    }

    public function askdestroy($id)
    {
        $customer = Customer::find($id);
        return view('customer.askdestroy', compact('customer'));
    }

    public function destroy($id)
    {
        $customer = Customer::find($id);
        $customer->delete();
        Contact::whereDoesntHave('customers')->delete();
        return redirect()->route('customer.index');
    }
}

resources/views/customer/askdestroy.blade.php
<div class="ui mini modal">
    <i class="close icon"></i>
    <div class="header">
        Elimina Cliente
    </div>
    <div class="content">
        <form method="POST" action="{{ route('customer.destroy', $customer->id) }}" class="ui form">
            @csrf
            @method('DELETE')

            <p>
                Sei sicuro di voler eliminare il cliente {{ $customer->name }}?
            </p>

            <button class="ui negative button" type="submit">Elimina</button>
        </form>
    </div>
</div>

resources/views/customer/contactselect.blade.php
<?php

if (!isset($selected_id))
    $selected_id = 0;

?>

@if($customer->contacts->count() != 0)
    <div class="field">
        <label>Contatto Primario</label>
        <div class="grouped fields">
            @foreach($customer->contacts as $index => $contact)
                <?php

                $checked = ($selected_id == $contact->id || ($selected_id == 0 && $index == 0));
                $actual_contacts = [];
                if (!empty($contact->phone))
                    $actual_contacts[] = $contact->phone;
                if (!empty($contact->mobile))
                    $actual_contacts[] = $contact->mobile;
                if (!empty($contact->email))
                    $actual_contacts[] = $contact->email;
                if (!empty($contact->email2))
                    $actual_contacts[] = $contact->email2;
                if (empty($actual_contacts))
                    $actual_contacts[] = 'Nessun Contatto!';

                ?>

                <div class="field">
                    <div class="ui {{ $checked ? 'checked' : '' }} toggle checkbox explicit">
                        <input type="radio" name="contact_id" tabindex="0" class="hidden" {{ $checked ? 'checked' : '' }} value="{{ $contact->id }}">
                        <label>{{ $contact->full_name }} ({{ join(', ', $actual_contacts) }})</label>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endif

resources/views/customer/edit.blade.php
<form method="POST" action="{{ $customer ? route('customer.update', $customer->id) : route('customer.store') }}" class="ui form">
    @csrf

    @if($customer)
        @method('PUT')
    @endif

    @include('customer.registry', ['customer' => $customer])

    <br>

    <div class="field contacts-table">
        <h4 class="ui horizontal divider header">
            <i class="phone icon"></i>
            Contatti
        </h4>

        <table id="contacts" class="ui basic table dynamic-table" data-max-rows="{{ $customer && $customer->type == 'person' ? 1 : 99 }}">
            <thead>
                <tr>
                    <th width="14%">Nome</th>
                    <th width="14%">Cognome</th>
                    <th width="14%">E-Mail</th>
                    <th width="14%">E-Mail Secondaria</th>
                    <th width="14%">Telefono</th>
                    <th width="14%">Cellulare</th>
                    <th width="15%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @if($customer)
                    @foreach($customer->contacts as $contact)
                        <tr>
                            <td>
                                <input type="hidden" name="contact_id[]" value="{{ $contact->id }}" class="id_into_table">
                                <span data-autocompletable-map="name">{{ $contact->name }}</span>
                            </td>
                            <td data-autocompletable-map="surname">{{ $contact->surname }}</td>
                            <td data-autocompletable-map="email">{{ $contact->email }}</td>
                            <td data-autocompletable-map="email2">{{ $contact->email2 }}</td>
                            <td data-autocompletable-map="phone">{{ $contact->phone }}</td>
                            <td data-autocompletable-map="mobile">{{ $contact->mobile }}</td>
                            <td>
                                <span class="pull-right">
                                    <button class="ui blue icon button async-modal" data-modal-url="{{ route('contact.edit', $contact->id) }}"><i class="address card icon"></i></button>
                                    <button class="ui red icon button remove-row"><i class="trash icon"></i></button>
                                </span>
                            </td>
                        </tr>
                    @endforeach
                @endif

                <tr class="reference-row">
                    <td>
                        <input type="hidden" name="contact_id[]" value="" data-autocompletable-map="id" class="id_into_table">
                        <span data-autocompletable-map="name"></span>
                    </td>
                    <td data-autocompletable-map="surname"></td>
                    <td data-autocompletable-map="email"></td>
                    <td data-autocompletable-map="email2"></td>
                    <td data-autocompletable-map="phone"></td>
                    <td data-autocompletable-map="mobile"></td>
                    <td>
                        <span class="pull-right">
                            <button class="ui blue icon button async-modal" data-autocompletable-map="edit_url" data-modal-url=""><i class="address card icon"></i></button>
                            <button class="ui red icon button remove-row"><i class="trash icon"></i></button>
                        </span>
                    </td>
                </tr>
            </tbody>
            @if($customer == null || $customer->type != 'person' || $customer->contacts->count() < 1)
                <tfoot>
                    <tr>
                        <td colspan="2">
                            <button class="ui orange basic button async-modal" data-modal-url="{{ route('contact.create') }}">Aggiungi Contatto</button>
                        </td>
                    </tr>
                </tfoot>
            @endif
        </table>
    </div>

    @if($customer)
        <h4 class="ui horizontal divider header">
            <i class="calendar icon"></i>
            Assegnazioni
        </h4>

        <table id="grants" class="ui basic table dynamic-table">
            <thead>
                <tr>
                    <th width="20%">Anno Sociale</th>
                    <th width="30%">Descrizione</th>
                    <th width="35%">Pagamenti</th>
                    <th width="15%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach($customer->grants as $grant)
                    <tr>
                        <td>
                            <input type="hidden" name="grant_id[]" value="{{ $grant->id }}" class="id_into_table">
                            <span data-autocompletable-map="year">{{ $grant->yearobj->name }}</span>
                        </td>
                        <td data-autocompletable-map="description">{{ $grant->description }}</td>
                        <td>
                            <ul data-autocompletable-map="payments">
                                @foreach($grant->payments as $payment)
                                    <li>{!! $payment->printable_full_description !!}</li>
                                @endforeach
                            </ul>
                        </td>
                        <td>
                            <span class="pull-right">
                                <button class="ui blue icon button async-modal" data-modal-url="{{ route('grant.edit', $grant->id) }}"><i class="zoom in icon"></i></button>
                                <button class="ui red icon button remove-row"><i class="trash icon"></i></button>
                            </span>
                        </td>
                    </tr>
                @endforeach

                <tr class="reference-row">
                    <td>
                        <input type="hidden" name="grant_id[]" data-autocompletable-map="id" class="id_into_table">
                        <span data-autocompletable-map="year"></span>
                    </td>
                    <td data-autocompletable-map="description"></td>
                    <td>
                        <ul data-autocompletable-map="payments"></ul>
                    </td>
                    <td>
                        <span class="pull-right">
                            <button class="ui blue icon button async-modal" data-autocompletable-map="edit_url" data-modal-url=""><i class="zoom in icon"></i></button>
                            <button class="ui red icon button remove-row"><i class="trash icon"></i></button>
                        </span>
                    </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4">
                        @if($customer->type != 'person' && $customer->contacts()->count() == 0)
                            <div class="ui message">
                                Occorre che il cliente abbia almeno un contatto prima di aprire nuove assegnazioni.
                            </div>
                        @else
                            <button class="ui orange basic button async-modal" data-modal-url="{{ route('grant.create', ['customer_id' => $customer->id]) }}">Aggiungi Assegnazione</button>
                        @endif
                    </td>
                </tr>
            </tfoot>
        </table>
    @endif

    <button class="ui positive button" type="submit">Salva</button>
    @if($customer)
        <a class="ui negative button right floated async-modal" href="#" data-modal-url="{{ route('customer.askdestroy', $customer->id) }}">Elimina</a>
    @endif
</form>

resources/views/customer/index.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.menu', ['active' => 'customers'])

    <div class="ui fluid container">
        <div class="ui grid fullwidth">
            <div class="four wide column">
                <div class="ui segment">
                    <div class="ui fluid buttons">
                        <a class="ui basic orange button async-portion" data-portion-url="{{ route('customer.create') }}" data-container-id="customer-details">Aggiungi Cliente</a>

                        @if($display == 'recent')
                            <a class="ui basic orange button" href="{{ route('customer.index', ['display' => 'all']) }}">Vedi Tutti</a>
                        @else
                            <a class="ui basic orange button" href="{{ route('customer.index', ['display' => 'recent']) }}">Vedi Recenti</a>
                        @endif
                    </div>

                    <p></p>

                    <div class="ui search">
                        <div class="ui fluid icon input">
                            <input class="prompt customer-filter" type="text" placeholder="Filtra">
                            <i class="search icon"></i>
                        </div>
                    </div>

                    <div class="ui celled list customer-list">
                        @foreach($customers as $customer)
                            <div class="item">
                                <a class="header async-portion" data-portion-url="{{ route('customer.edit', $customer->id) }}" data-container-id="customer-details">{{ $customer->name }}</a>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>

            <div class="twelve wide column" id="customer-details">
                <h2 class="ui center aligned icon header">
                    <i class="circular users icon"></i>
                    Seleziona o crea un cliente.
                </h2>
            </div>
        </div>
    </div>
@endsection

resources/views/customer/registry.blade.php
<?php

if(!isset($prefix))
    $prefix = '';

?>

<div class="customer-base-registry-form">
    <div class="two fields">
        <div class="required six wide field">
            <label>Nome</label>
            <input type="text" name="{{ $prefix }}name" value="{{ $customer ? $customer->name : '' }}" class="remote-unique" data-unique-test="{{ route('customer.search') }}" data-unique-test-exclude="{{ $customer ? $customer->id : '' }}" required>
        </div>

        <div class="required ten wide field customer-type-select">
            <label>Tipo</label>
            <div class="inline fields">
                <div class="field">
                    <div class="ui radio checkbox {{ $customer && $customer->type == 'private' ? 'active' : '' }}">
                        <input type="radio" name="{{ $prefix }}type" value="private" class="hidden" {{ $customer && $customer->type == 'private' ? 'checked' : '' }} required>
                        <label>Privato</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox {{ $customer && $customer->type == 'association' ? 'active' : '' }}">
                        <input type="radio" name="{{ $prefix }}type" value="association" class="hidden" {{ $customer && $customer->type == 'association' ? 'checked' : '' }} required>
                        <label>Associazione</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox {{ $customer && $customer->type == 'cooperative' ? 'active' : '' }}">
                        <input type="radio" name="{{ $prefix }}type" value="cooperative" class="hidden" {{ $customer && $customer->type == 'cooperative' ? 'checked' : '' }} required>
                        <label>Cooperativa</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox {{ $customer && $customer->type == 'group' ? 'active' : '' }}">
                        <input type="radio" name="{{ $prefix }}type" value="group" class="hidden" {{ $customer && $customer->type == 'group' ? 'checked' : '' }} required>
                        <label>Gruppo</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox {{ $customer && $customer->type == 'person' ? 'active' : '' }}">
                        <input type="radio" name="{{ $prefix }}type" value="person" class="hidden" {{ $customer && $customer->type == 'person' ? 'checked' : '' }} required>
                        <label>Persona Fisica</label>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if($customer == null || $customer->type != 'person')
        <div class="three fields">
            <div class="field">
                <label>Indirizzo</label>
                <input type="text" name="{{ $prefix }}address" value="{{ $customer ? $customer->address : '' }}">
            </div>
            <div class="field">
                <label>Città</label>
                <input type="text" name="{{ $prefix }}city" value="{{ $customer ? $customer->city : '' }}">
            </div>
            <div class="field">
                <label>CAP</label>
                <input type="text" name="{{ $prefix }}zip" value="{{ $customer ? $customer->zip : '' }}">
            </div>
        </div>

        <div class="two fields">
            <div class="field">
                <label>Codice Fiscale</label>
                <input type="text" name="{{ $prefix }}taxcode" value="{{ $customer ? $customer->taxcode : '' }}">
            </div>
            <div class="field">
                <label>Partita IVA</label>
                <input type="text" name="{{ $prefix }}vat" value="{{ $customer ? $customer->vat : '' }}">
            </div>
        </div>

        <div class="three fields">
            <div class="field">
                <label>Telefono</label>
                <input type="text" name="{{ $prefix }}phone" value="{{ $customer ? $customer->phone : '' }}">
            </div>
            <div class="field">
                <label>E-Mail</label>
                <input type="email" name="{{ $prefix }}email" value="{{ $customer ? $customer->email : '' }}">
            </div>
            <div class="field">
                <label>Website</label>
                <input type="text" name="{{ $prefix }}website" value="{{ $customer ? $customer->website : '' }}">
            </div>
        </div>
    @endif

    <div class="field">
        <label>Note Cliente</label>
        <textarea name="{{ $prefix }}note" rows="3">{{ $customer ? $customer->notes : '' }}</textarea>
    </div>
</div>

resources/views/customer/search.blade.php
<div>
    <div class="field ui search customer_complete">
        <div class="ui action input">
            <input class="prompt" type="text" name="customer_name" required>
            <input type="hidden" name="customer_id" value="">

            @if(isset($can_create_on))
                <button class="ui positive button async-portion" data-portion-url="{{ route('booking.wizard', 'new_customer') }}" data-container-id="{{ $can_create_on }}">Crea Nuovo Cliente</button>
            @endif
        </div>
        <div class="results"></div>
    </div>
</div>